[tool.poetry]
name = "project-6"
version = "0.1.0"
description = "sqlalchemy"
authors = ["Strike_Squad"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.23"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
